server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: repairlist-service
          uri: lb://repairlist-service
          predicates:
            - Path=/api/repairlist/**
        - id: repairvehicle-service
          uri: lb://repairvehicle-service
          predicates:
            - Path=/api/repairvehicles/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicles/**
