server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.105:5432/repairlist
    username: postgres
    password: postgres
    
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/