apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server-deployment
  labels:
    app: frontend-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-server-deployment
  template:
    metadata:
      labels:
        app: frontend-server-deployment
    spec:
      containers:
      - name: frontend-server
        image: donex/autofix-ms-frontend-image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        env:
        - name: REACT_APP_BACKEND_SERVER
          valueFrom:
            configMapKeyRef:
              name: frontend-config-map
              key: BACKEND-HOST
        - name: REACT_APP_BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: frontend-config-map
              key: BACKEND-PORT
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx-config-map
          items:
          - key: nginx.conf
            path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-server-service
  labels:
    app: frontend-server-service
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: frontend-server-deployment
  type: LoadBalancer
