apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-repairlist-deployment
  labels:
    app: ms-repairlist-deployment
spec:
  selector:
    matchLabels:
      app: ms-repairlist-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: ms-repairlist-deployment
    spec:
      containers:
        - name: ms-repairlist
          image: donex/autofix-ms-repairlist-image
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPAIRLIST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPAIRLIST
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REPAIRLIST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPAIRLIST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPAIRLIST