apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-report-deployment
  labels:
    app: ms-report-deployment
spec:
  selector:
    matchLabels:
      app: ms-report-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: ms-report-deployment
    spec:
      containers:
        - name: ms-report
          image: donex/autofix-ms-report-image
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"