apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-repairvehicle-deployment
  labels:
    app: ms-repairvehicle-deployment
spec:
  selector:
    matchLabels:
      app: ms-repairvehicle-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: ms-repairvehicle-deployment
    spec:
      containers:
        - name: ms-repairvehicle
          image: donex/autofix-ms-repairvehicle-image
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REPAIRVEHICLE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REPAIRVEHICLE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REPAIRVEHICLE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REPAIRVEHICLE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REPAIRVEHICLE