apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-vehicle-deployment
  labels:
    app: ms-vehicle-deployment
spec:
  selector:
    matchLabels:
      app: ms-vehicle-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: ms-vehicle-deployment
    spec:
      containers:
        - name: ms-vehicle
          image: donex/autofix-ms-vehicle-image
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_VEHICLE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_VEHICLE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_VEHICLE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_VEHICLE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_VEHICLE